version: '3'
services:
    postgres:
        container_name: database
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSRTGRES_DATABASE: stockMestre

        ports:
           - '5432:5432'

    api:
        container_name: api
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./:/www


volumes:
    postgres_data:

