version: '3'
services:
    postgres:
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: root
     
        expose:
           - 5432:5432

volumes:
    postgres_data:

