"""empty message

Revision ID: d881f7ea15bb
Revises: c27fb46e04f9
Create Date: 2024-01-03 15:09:21.601435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd881f7ea15bb'
down_revision: Union[str, None] = 'c27fb46e04f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """INSERT INTO state (name, country_id) VALUES
        ('Acre', 1), ('Alagoas', 1), ('Amapá', 1), ('Amazonas', 1),
        ('Bahia', 1), ('Ceará', 1), ('Espírito Santo', 1),
        ('Goiás', 1), ('Maranhão', 1), ('Mato Grosso', 1),
        ('Mato Grosso do Sul', 1), ('Minas Gerais', 1),
        ('Pará', 1), ('Paraíba', 1), ('Paraná', 1),
        ('Pernambuco', 1), ('Piauí', 1), ('Rio de Janeiro', 1),
        ('Rio Grande do Norte', 1), ('Rio Grande do Sul', 1),
        ('Rondônia', 1), ('Roraima', 1), ('Santa Catarina', 1),
        ('São Paulo', 1), ('Sergipe', 1), ('Tocantins', 1),
        ('Distrito Federal', 1)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
