"""empty message

Revision ID: 212ba973dfdc
Revises: 66eb421ba464
Create Date: 2024-01-03 14:54:21.609052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212ba973dfdc'
down_revision: Union[str, None] = '66eb421ba464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""INSERT INTO continent (name) VALUES ('South America')""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
