"""empty message

Revision ID: e140491ce972
Revises: d881f7ea15bb
Create Date: 2024-01-03 17:53:57.606444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e140491ce972'
down_revision: Union[str, None] = 'd881f7ea15bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('continent_unique', 'continent', ['name'])
    op.create_unique_constraint('country_unique', 'country', ['name'])
    op.create_unique_constraint('department_unique', 'department', ['name'])
    op.create_unique_constraint('person_unique', 'person', ['document'])
    op.create_unique_constraint('prod_department_unique', 'product', ['name', 'department_id'])
    op.create_unique_constraint('country_state', 'state', ['name', 'country_id'])
    op.create_unique_constraint('company_prod_unique', 'stoke', ['company_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_prod_unique', 'stoke', type_='unique')
    op.drop_constraint('country_state', 'state', type_='unique')
    op.drop_constraint('prod_department_unique', 'product', type_='unique')
    op.drop_constraint('person_unique', 'person', type_='unique')
    op.drop_constraint('department_unique', 'department', type_='unique')
    op.drop_constraint('country_unique', 'country', type_='unique')
    op.drop_constraint('continent_unique', 'continent', type_='unique')
    # ### end Alembic commands ###
